pdfs:
  - title: "basic-text"
    section: "General"
    number: "PDF-001"
    date: "2023-11-12"
    summary: "A simple one-page document with basic text formatting. Perfect for testing PDF readers and basic PDF handling."
    tags: ["basic", "text", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/basic-text.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/basic-text.pdf"
    pdf_size: "72.9 KB"
  - title: "sample-report"
    section: "General"
    number: "PDF-002"
    date: "2024-01-15"
    summary: "A multi-page report with text, images, and tables. Ideal for testing pagination and complex layout rendering."
    tags: ["report", "multi-page", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-report.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-report.pdf"
    pdf_size: "2.39 MB"
  - title: "image-doc"
    section: "General"
    number: "PDF-003"
    date: "2023-12-05"
    summary: "Document with high-resolution images. Great for testing image extraction and PDF optimization techniques."
    tags: ["image", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/image-doc.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/image-doc.pdf"
    pdf_size: "7.97 MB"
  - title: "large-doc"
    section: "General"
    number: "PDF-004"
    date: "2024-02-20"
    summary: "A large, content-rich document. Ideal for testing PDF loading times and memory handling."
    tags: ["large", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/large-doc.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/large-doc.pdf"
    pdf_size: "36.8 MB"
  - title: "dev-example"
    section: "General"
    number: "PDF-005"
    date: "2023-10-28"
    summary: "A specially crafted PDF showcasing various PDF features. Ideal for developers learning PDF manipulation."
    tags: ["developer", "example", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/dev-example.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/dev-example.pdf"
    pdf_size: "690 KB"
  - title: "sample-pdf-a4-size"
    section: "General"
    number: "PDF-006"
    date: "2023-09-14"
    summary: "A4 size sample PDF. Useful for layout and print tests."
    tags: ["a4", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-pdf-a4-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-pdf-a4-size.pdf"
    pdf_size: "151 KB"
  - title: "sample-pdf-letter-size"
    section: "General"
    number: "PDF-007"
    date: "2023-08-22"
    summary: "Letter size sample PDF. Useful for layout and print tests."
    tags: ["letter", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-pdf-letter-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-pdf-letter-size.pdf"
    pdf_size: "151 KB"
  - title: "sample-pdf-legal-size"
    section: "General"
    number: "PDF-008"
    date: "2023-07-30"
    summary: "Legal size sample PDF. Useful for layout and print tests."
    tags: ["legal", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-pdf-legal-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-pdf-legal-size.pdf"
    pdf_size: "155 KB"
  - title: "sample-5-page-pdf-a4-size"
    section: "General"
    number: "PDF-009"
    date: "2023-11-01"
    summary: "A 5-page A4 size sample PDF. Useful for multi-page layout tests."
    tags: ["5-page", "a4", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-5-page-pdf-a4-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-5-page-pdf-a4-size.pdf"
    pdf_size: "120 KB"
  - title: "sample-10-page-pdf-a4-size"
    section: "General"
    number: "PDF-010"
    date: "2024-03-10"
    summary: "A 10-page A4 size sample PDF. Useful for multi-page layout tests."
    tags: ["10-page", "a4", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-10-page-pdf-a4-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-10-page-pdf-a4-size.pdf"
    pdf_size: "2 MB"
  - title: "sample-text-only-pdf-a4-size"
    section: "General"
    number: "PDF-011"
    date: "2023-10-10"
    summary: "A text-only A4 size sample PDF. Useful for text extraction and OCR tests."
    tags: ["text-only", "a4", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-text-only-pdf-a4-size.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-text-only-pdf-a4-size.pdf"
    pdf_size: "100 KB"
  - title: "sample-pdf-a4-size-65kb"
    section: "General"
    number: "PDF-012"
    date: "2023-09-25"
    summary: "A small A4 size sample PDF (65KB). Useful for lightweight PDF tests."
    tags: ["a4", "sample", "test", "pdf", "all", "budget", "tax", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/sample-pdf-a4-size-65kb.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/sample-pdf-a4-size-65kb.pdf"
    pdf_size: "64.6 KB"
  - title: "Budget 2024 Allocation"
    section: "Budget Orders"
    number: "BO-2024-01"
    date: "2024-04-01"
    summary: "Annual budget allocation for FY 2024-25."
    tags: ["budget", "allocation", "2024", "fy", "annual", "pdf", "all", "budget"]
    pdf: "https://media.finock.ssnk.in/pdfs/budget1.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/budget1.pdf"
    pdf_size: "2.39 MB"
  - title: "Supplementary Grant"
    section: "Budget Orders"
    number: "BO-2024-02"
    date: "2024-05-15"
    summary: "Supplementary grant for infrastructure projects."
    tags: ["budget", "supplementary", "grant", "infrastructure", "projects", "pdf", "all", "budget"]
    pdf: "https://media.finock.ssnk.in/pdfs/budget2.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/budget2.pdf"
    pdf_size: "2.39 MB"
  - title: "GST Amendment"
    section: "Taxation"
    number: "TX-2024-01"
    date: "2024-03-10"
    summary: "Amendment to GST rates for select goods."
    tags: ["taxation", "gst", "amendment", "rates", "goods", "pdf", "all", "tax"]
    pdf: "https://media.finock.ssnk.in/pdfs/tax1.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/tax1.pdf"
    pdf_size: "2.39 MB"
  - title: "Income Tax Slab Revision"
    section: "Taxation"
    number: "TX-2024-02"
    date: "2024-02-20"
    summary: "Revision of income tax slabs for FY 2024-25."
    tags: ["taxation", "income", "tax", "slab", "revision", "fy", "2024", "pdf", "all", "tax"]
    pdf: "https://media.finock.ssnk.in/pdfs/tax2.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/tax2.pdf"
    pdf_size: "2.39 MB"
  - title: "Departmental Expenditure"
    section: "Expenditure"
    number: "EX-2024-01"
    date: "2024-01-12"
    summary: "Expenditure details for Q1 2024."
    tags: ["expenditure", "departmental", "q1", "2024", "details", "pdf", "all", "expenditure"]
    pdf: "https://media.finock.ssnk.in/pdfs/exp1.pdf"
    pdf_path: "https://media.finock.ssnk.in/pdfs/exp1.pdf"
    pdf_size: "2.39 MB"
